/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 17-Jul-2019 3:52:59 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0
; 
/* Drop Tables */

DROP TABLE IF EXISTS `AdministradorBanco` CASCADE
;

DROP TABLE IF EXISTS `Banco` CASCADE
;

DROP TABLE IF EXISTS `Capacidad` CASCADE
;

DROP TABLE IF EXISTS `Donacion` CASCADE
;

DROP TABLE IF EXISTS `Donante` CASCADE
;

DROP TABLE IF EXISTS `Estado` CASCADE
;

DROP TABLE IF EXISTS `HistorialRegistro` CASCADE
;

DROP TABLE IF EXISTS `Proveedor` CASCADE
;

DROP TABLE IF EXISTS `RegistroAlmacenamiento` CASCADE
;

DROP TABLE IF EXISTS `RH` CASCADE
;

DROP TABLE IF EXISTS `Telefono` CASCADE
;

/* Create Tables */

CREATE TABLE `AdministradorBanco`
(
	`idAdministrador` INT NOT NULL AUTO_INCREMENT,
	`idBanco` INT NOT NULL,
	`nombres` VARCHAR(100) NOT NULL,
	`apellidos` VARCHAR(100) NOT NULL,
	`hash` VARCHAR(32) NOT NULL,
	CONSTRAINT `PK_AdministradorBanco` PRIMARY KEY (`idAdministrador` ASC)
)

;

CREATE TABLE `Banco`
(
	`idBanco` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	`direccion` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_Banco` PRIMARY KEY (`idBanco` ASC)
)

;

CREATE TABLE `Capacidad`
(
	`idCapacidad` INT NOT NULL AUTO_INCREMENT,
	`idBanco` INT NOT NULL,
	`max` DOUBLE(10,2) NOT NULL,
	`min` DOUBLE(10,2) NOT NULL,
	`idRH` INT NOT NULL,
	CONSTRAINT `PK_Capacidad` PRIMARY KEY (`idCapacidad` ASC)
)

;

CREATE TABLE `Donacion`
(
	`idDonacion` INT NOT NULL AUTO_INCREMENT,
	`idDonante` BIGINT NOT NULL,
	`idProveedor` INT NOT NULL,
	`fecha` DATETIME NOT NULL,
	`cantidad` DECIMAL(10,2) NOT NULL,
	CONSTRAINT `PK_Donacion` PRIMARY KEY (`idDonacion` ASC)
)

;

CREATE TABLE `Donante`
(
	`cedula` BIGINT NOT NULL AUTO_INCREMENT,
	`nombres` VARCHAR(100) NOT NULL,
	`apellidos` VARCHAR(100) NOT NULL,
	`idRH` INT NOT NULL,
	`correo` VARCHAR(75) NOT NULL,
	`direccion` VARCHAR(100) NOT NULL,
	CONSTRAINT `PK_Donante` PRIMARY KEY (`cedula` ASC)
)

;

CREATE TABLE `Estado`
(
	`idEstado` INT NOT NULL AUTO_INCREMENT,
	`nombre` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Estado` PRIMARY KEY (`idEstado` ASC)
)

;

CREATE TABLE `HistorialRegistro`
(
	`idHistorial` INT NOT NULL AUTO_INCREMENT,
	`idEstado` INT NOT NULL,
	`idRegistro` INT NOT NULL,
	`fecha` DATE NOT NULL,
	`idAdministrador` INT NOT NULL,
	CONSTRAINT `PK_HistorialRegistro` PRIMARY KEY (`idHistorial` ASC)
)

;

CREATE TABLE `Proveedor`
(
	`nit` INT NOT NULL,
	`razonSocial` VARCHAR(50) NOT NULL,
	`direccion` VARCHAR(50) NOT NULL,
	`numeroContacto` VARCHAR(50) NOT NULL,
	`limiteAcreditacion` DATE NOT NULL,
	`hash` VARCHAR(32) NOT NULL,
	CONSTRAINT `PK_Proveedor` PRIMARY KEY (`nit` ASC)
)

;

CREATE TABLE `RegistroAlmacenamiento`
(
	`idRegistro` INT NOT NULL AUTO_INCREMENT,
	`idDonacion` INT NOT NULL,
	`idBanco` INT NOT NULL,
	CONSTRAINT `PK_RegistroAlmacenamiento` PRIMARY KEY (`idRegistro` ASC)
)

;

CREATE TABLE `RH`
(
	`idRH` INT NOT NULL AUTO_INCREMENT,
	`tipo` VARCHAR(5) NOT NULL,
	`factor` VARCHAR(25) NOT NULL,
	CONSTRAINT `PK_RH` PRIMARY KEY (`idRH` ASC)
)

;

CREATE TABLE `Telefono`
(
	`idTelefono` INT NOT NULL AUTO_INCREMENT,
	`donanteAsociado` BIGINT NOT NULL,
	`numero` VARCHAR(50) NOT NULL,
	`tipo` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_Telefono` PRIMARY KEY (`idTelefono` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `AdministradorBanco` 
 ADD INDEX `IXFK_AdministradorBanco_Banco` (`idBanco` ASC)
;

ALTER TABLE `Capacidad` 
 ADD INDEX `IXFK_Capacidad_Banco` (`idBanco` ASC)
;

ALTER TABLE `Capacidad` 
 ADD INDEX `IXFK_Capacidad_RH` (`idRH` ASC)
;

ALTER TABLE `Donacion` 
 ADD INDEX `IXFK_Donacion_Donante` (`idDonante` ASC)
;

ALTER TABLE `Donacion` 
 ADD INDEX `IXFK_Donacion_Proveedor` (`idProveedor` ASC)
;

ALTER TABLE `Donante` 
 ADD INDEX `IXFK_Donante_RH` (`idRH` ASC)
;

ALTER TABLE `HistorialRegistro` 
 ADD INDEX `IXFK_HistorialRegistro_AdministradorBanco` (`idAdministrador` ASC)
;

ALTER TABLE `HistorialRegistro` 
 ADD INDEX `IXFK_HistorialRegistro_Estado` (`idEstado` ASC)
;

ALTER TABLE `HistorialRegistro` 
 ADD INDEX `IXFK_HistorialRegistro_RegistroAlmacenamiento` (`idRegistro` ASC)
;

ALTER TABLE `RegistroAlmacenamiento` 
 ADD INDEX `IXFK_RegistroAlmacenamiento_Banco` (`idBanco` ASC)
;

ALTER TABLE `RegistroAlmacenamiento` 
 ADD INDEX `IXFK_RegistroAlmacenamiento_Donacion` (`idDonacion` ASC)
;

ALTER TABLE `Telefono` 
 ADD INDEX `IXFK_Telefono_Donante` (`donanteAsociado` ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE `AdministradorBanco` 
 ADD CONSTRAINT `FK_AdministradorBanco_Banco`
	FOREIGN KEY (`idBanco`) REFERENCES `Banco` (`idBanco`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Capacidad` 
 ADD CONSTRAINT `FK_Capacidad_Banco`
	FOREIGN KEY (`idBanco`) REFERENCES `Banco` (`idBanco`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `Capacidad` 
 ADD CONSTRAINT `FK_Capacidad_RH`
	FOREIGN KEY (`idRH`) REFERENCES `RH` (`idRH`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `Donacion` 
 ADD CONSTRAINT `FK_Donacion_Donante`
	FOREIGN KEY (`idDonante`) REFERENCES `Donante` (`cedula`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `Donacion` 
 ADD CONSTRAINT `FK_Donacion_Proveedor`
	FOREIGN KEY (`idProveedor`) REFERENCES `Proveedor` (`nit`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `Donante` 
 ADD CONSTRAINT `FK_Donante_RH`
	FOREIGN KEY (`idRH`) REFERENCES `RH` (`idRH`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `HistorialRegistro` 
 ADD CONSTRAINT `FK_HistorialRegistro_AdministradorBanco`
	FOREIGN KEY (`idAdministrador`) REFERENCES `AdministradorBanco` (`idAdministrador`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `HistorialRegistro` 
 ADD CONSTRAINT `FK_HistorialRegistro_Estado`
	FOREIGN KEY (`idEstado`) REFERENCES `Estado` (`idEstado`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `HistorialRegistro` 
 ADD CONSTRAINT `FK_HistorialRegistro_RegistroAlmacenamiento`
	FOREIGN KEY (`idRegistro`) REFERENCES `RegistroAlmacenamiento` (`idRegistro`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `RegistroAlmacenamiento` 
 ADD CONSTRAINT `FK_RegistroAlmacenamiento_Banco`
	FOREIGN KEY (`idBanco`) REFERENCES `Banco` (`idBanco`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `RegistroAlmacenamiento` 
 ADD CONSTRAINT `FK_RegistroAlmacenamiento_Donacion`
	FOREIGN KEY (`idDonacion`) REFERENCES `Donacion` (`idDonacion`) ON DELETE Cascade ON UPDATE Restrict
;

ALTER TABLE `Telefono` 
 ADD CONSTRAINT `FK_Telefono_Donante`
	FOREIGN KEY (`donanteAsociado`) REFERENCES `Donante` (`cedula`) ON DELETE Cascade ON UPDATE Restrict
;

SET FOREIGN_KEY_CHECKS=1
; 
